### ISSUE TITLE
勘误：场景8：化繁为简——信息提取

### ISSUE THREAD

**Issue by wangjiatao** [thinkingjimmy/Learning-Prompt#1]
“Prompt 有点长，我解释下，它是让 AI 将文章里的重点内容进行抽离，并将其根据特定格式进行输出。要求将文章里提到的公司、人名、主题都按照 comma separated list（按逗号空格分开）的方式 **萝莉** 出来。” 
萝莉--罗列

**Comment by thinkingjimmy** [comment]
感谢提醒

**Comment by wangjiatao** [comment]
拱手，感谢 您的无私分享。
