### ISSUE TITLE
推理答案是否错误

### ISSUE THREAD

**Issue by duyujie2019** [thinkingjimmy/Learning-Prompt#10]
陈述(1):售价减去房地产经纪人的佣金为84,600美元。

给定:佣金是售价的6%。

公式:佣金 = 售价 × 6% = 售价 × 0.06

根据陈述(1):售价 - 佣金 = 84,600

将公式代入:售价 - 售价 × 0.06 = 84,600

解得:售价 = 84,600 / (1 - 0.06) = 90,000美元

陈述(2):购买价是36,000美元,是售价的 250%。

给定:购买价 = 36,000;购买价是售价的250%。

公式:购买价 = 售价 × 250% = 售价 × 2.5

将给定条件代入公式:36,000 = 售价 × 2.5

解得:售价 = 36,000 / 2.5 = 14,400美元

综上,仅陈述(1)足以回答问题,售价是90,000美元。

但仅陈述(2)不能回答问题,因为根据陈述(2)得出的售价是14,400美元,与givne的佣金率6%不符。

因此,选择A:仅陈述(1)足以回答问题,但仅陈述(2)不能回答问题。

所以答案是:
A
--------------
设该房子的售价为x美元。

根据题意可得：
(1) x - 0.06x = 84600
(2) x = 1/2.5 * 36000

化简后可得：
(1) 0.94x = 84600
x ≈ 90000
(2) x = 14400

因此，只有陈述（1）足以回答问题，选项（A）为正确答案。

**Comment by boofw** [comment]
这里是因为题目的中文翻译错误，原文售价是购买价的250%

**Comment by thinkingjimmy** [comment]
抱歉，是翻译错误，boofw 的理解是正确的。
