### ISSUE TITLE
可否转载文章至公众号？

### ISSUE THREAD

**Issue by ferstar** [thinkingjimmy/Learning-Prompt#13]
您好，我有一个工具类的公众号：scihubot

读到您 [这篇文章](https://learningprompt.wiki/docs/tutorial-insight/AI%20%E6%9C%89%E5%8F%AF%E8%83%BD%E6%94%B9%E5%8F%98%E4%BA%BA%E7%9A%84%E5%AD%A6%E4%B9%A0%E6%96%B9%E5%BC%8F%E5%90%97%EF%BC%9F/%E6%9C%89%E5%8F%AF%E8%83%BD%E6%94%B9%E5%8F%98%E4%BA%BA%E7%9A%84%E9%98%85%E8%AF%BB%E6%96%B9%E5%BC%8F%E5%90%97%EF%BC%9F) 非常有启发，觉得也应该比较适合我公众号的受众「基本都是学生」。厚颜求个转发，不知可否？

拜谢！

**Comment by thinkingjimmy** [comment]
只要注明来源（需标注 Github 或网站链接）即可。

BTW 也感谢你的传播和分享。
