### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by CraneHuang6** [thinkingjimmy/Learning-Prompt#15]
感谢这么详细的教程！ 

捉虫，技巧6第一段，“其实在场景7种，你也可以用到这个技巧。”

另外，技巧5使用 ”“” 符号将指令和需要处理的文本分开。在OpenAI 的 API最佳实践文档中，除了"""，还有###也可以作为文本分隔符。
不知道有什么区别，个人更喜欢用#号。

**Comment by thinkingjimmy** [comment]
感谢提醒，已修改。因为我有的时候会用 # 作为格式示例，太多 # 的话 prompt 会看起来比较晕 😂，所以才没介绍。但这样也不好，应该让大家知道全面的信息，我已补充。
