### ISSUE TITLE
其他技巧页面可以再增加一些说明，有点读不懂

### ISSUE THREAD

**Issue by yingyingzux** [thinkingjimmy/Learning-Prompt#16]
https://learningprompt.wiki/docs/tutorial-tips/%E6%8A%80%E5%B7%A79%EF%BC%9A%E5%85%B6%E4%BB%96

这一页最后给了个output，看起来是回答最后一个问题。那么，前面有？的问题模型就自动不处理了吗？整体上感觉这一页没有读懂，也不太清楚这个技巧在什么时候会有用，可以再增加一些解释，谢谢。

**Comment by thinkingjimmy** [comment]
感谢回复。你如果问 ChatGPT 一些奇怪的问题，ChatGPT 就会说一些胡话。而 ？ 的作用就是告诉它，当遇到不知道的问题时，该回答「不知道」，比如例子中 What is Devz9 里的 Devz9 是个胡乱造出来的词，当遇到这类问题时，模型就会回复 ?
<img width="679" alt="image" src="https://user-images.githubusercontent.com/37492595/227750835-f6a58c10-0ff4-4efa-9ef3-4cc6ae6914d8.png">

**Comment by thinkingjimmy** [comment]
看了下文档里的例子，的确不是很好，已修改。
