### ISSUE TITLE
自定义知识库案例里的上传离线数据教程，点击链接后仍然是当前页。

### ISSUE THREAD

**Issue by Dorixed** [thinkingjimmy/Learning-Prompt#19]
![image](https://user-images.githubusercontent.com/122142944/228193519-70854dcc-fa18-4c45-b652-af10c0f38dc6.png)

我导入的是我的论文初稿，docx格式，但是不管是问什么问题回复都是none，因此我认为可能是不支持这种数据格式，但离线数据教程又点不开，希望作者能解答一下疑惑。
![image](https://user-images.githubusercontent.com/122142944/228193841-eb8dadff-c543-4863-8ff1-ad36b65e2702.png)

**Comment by thinkingjimmy** [comment]
Sorry 最近在肝图片类的教程，现在才回复。教程在这里：[搭建基于知识库内容的机器人](https://learningprompt.wiki/docs/tutorial-extras/%E6%90%AD%E5%BB%BA%E5%9F%BA%E4%BA%8E%E7%9F%A5%E8%AF%86%E5%BA%93%E5%86%85%E5%AE%B9%E7%9A%84%E6%9C%BA%E5%99%A8%E4%BA%BA)

**Comment by Dorixed** [comment]
我已收到，感谢你的来信！
