### ISSUE TITLE
错别字2个

### ISSUE THREAD

**Issue by wangschang** [thinkingjimmy/Learning-Prompt#24]
1. https://learningprompt.wiki/docs/tutorial-basics/%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%20&%20%E4%BD%BF%E7%94%A8%E6%8A%80%E5%B7%A7/%E5%9C%BA%E6%99%AF8%EF%BC%9A%E5%8C%96%E7%B9%81%E4%B8%BA%E7%AE%80%E2%80%94%E2%80%94%E4%BF%A1%E6%81%AF%E6%8F%90%E5%8F%96

技巧6：通过示例来阐述需要输出的格式  下面

其实在场景7_种_，你也可以用到这个技巧

2. https://learningprompt.wiki/docs/tutorial-extras/OpenAI%20Playground%20%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

你会在界面的右侧看到以下几个参数：

Mode： 最近_跟_新了第四种 Chat 模式

**Comment by thinkingjimmy** [comment]
感谢支持
