### ISSUE TITLE
语义不太通顺

### ISSUE THREAD

**Issue by xuzhe1111** [thinkingjimmy/Learning-Prompt#28]
在“Zero-Shot Prompts”中，

最后一段：

'''
另外，根据 Wei 等人在 [2022 年的论文](https://arxiv.org/pdf/2201.11903.pdf)表明，还有它仅在大于等于 100B 参数的模型中使用才会有效。如果你使用的是小样本模型，这个方法不会生效。
'''

"另外“和”还有“在语义上重复了，可以考虑删掉”还有“。

祝好，感谢

**Comment by thinkingjimmy** [comment]
感谢提醒，已修复。
