### ISSUE TITLE
建议给 “需要学习 PE 吗？” 章节添加上关于使用 AI 编写 Prompt 的案例。

### ISSUE THREAD

**Issue by zbysir** [thinkingjimmy/Learning-Prompt#3]
如果人能写出各个案例的最佳 Prompt，那么收集一下给 AI 训练，那么 AI 很快也能学会如何生成 Prompt，所以我在想是不是 PE 的寿命还可能更短。

比如这个模型：https://huggingface.co/spaces/merve/ChatGPT-prompt-generator

我感觉这个话题还挺有意思的，可以的话也希望加到文章中引起大家一起思考。（我没那个文笔，所以只能提建议，而不是贡献）

**Comment by thinkingjimmy** [comment]
1. 坦率说来，我认为 GUI 更有可能缩短 PE 的寿命，写字的效率还是太低了。
2. 但对于研发和研究人员来说， PE 的寿命应该挺长的，AI 生成 Prompt 我认为可能还需要再看看，因为不管怎样，从原理的角度来看，目前这类语言模型是没有创造力的。可能还需要持续观察下。

另外我后续会每周更新一篇博文，但更多记录的是 AI 的实际使用上。
BTW 感谢你的提供的案例，

**Comment by zbysir** [comment]
> 1. 坦率说来，我认为 GUI 更有可能缩短 PE 的寿命，写字的效率还是太低了。
> 2. 但对于研发和研究人员来说， PE 的寿命应该挺长的，AI 生成 Prompt 我认为可能还需要再看看，因为不管怎样，从原理的角度来看，目前这类语言模型是没有创造力的。可能还需要持续观察下。
> 
> 另外我后续会每周更新一篇博文，但更多记录的是 AI 的实际使用上。 BTW 感谢你的提供的案例，

博文在哪里可以看呀？
