### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by xiaodi007** [thinkingjimmy/Learning-Prompt#32]
https://learningprompt.wiki/docs/tutorial-insight/AI%20Summary%20%E4%BC%9A%E5%8F%96%E4%BB%A3%E4%BA%BA%E5%B7%A5%20Summary%20%E5%90%97%EF%BC%9F
缺点五：AI 并不知道什么是重点。
如果前面 4 个缺点，在技术上未来应该能解决（比如 OpenAI 放开~~先知道~~ 8K 个 Token）

改为 -> 限制到

**Comment by thinkingjimmy** [comment]
感谢，已修复
