### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by pengyyn** [thinkingjimmy/Learning-Prompt#34]
![错别字1](https://user-images.githubusercontent.com/22237664/229352970-62e27582-4a44-4752-bfe5-361cf4a350b5.jpg)
https://learningprompt.wiki/docs/tutorial-files/%E5%80%BC%E5%BE%97%E5%B0%9D%E8%AF%95%E7%9A%84%E5%9C%BA%E6%99%AF#%E5%B0%86%E5%A4%96%E9%83%A8%E6%95%B0%E6%8D%AE%E5%BA%93%E6%95%B0%E6%8D%AE%E6%8F%90%E4%BE%9B%E7%BB%99%E6%A8%A1%E5%9E%8B

**Comment by thinkingjimmy** [comment]
感谢 已更正
