### ISSUE TITLE
技巧9"在示例里加入特定符号，让模型知道如何处理特殊情况"不能生效

### ISSUE THREAD

**Issue by lwtao** [thinkingjimmy/Learning-Prompt#53]
你好，按照示例操作，发现chatgpt的回答并未符合预期
![image](https://user-images.githubusercontent.com/1950735/230520507-12b36f66-56bb-46c6-9c38-5ba734bc97f8.png)

**Comment by thinkingjimmy** [comment]
感谢提醒。我看了下，在 playground 里可以复现，但直接在 ChatGPT 里会回到更明确的答案。已在文档里补充。
