### ISSUE TITLE
Midjourney 官方 FAQ 翻译笔误

### ISSUE THREAD

**Issue by chrisnotion** [thinkingjimmy/Learning-Prompt#62]
https://learningprompt.wiki/docs/midjourney/mj-tutorial-extras/midjourney-official-faq
"意思就是会影响，有一定作用，但利大于弊。加入这些词，反而会破坏你的 prompt，"
此处笔误,应该是弊大于利.

**Comment by thinkingjimmy** [comment]
感谢提醒，已修复
