### ISSUE TITLE
首页”ChatGPT 教程“和”Midjourney 教程“路径错误打不开

### ISSUE THREAD

**Issue by xujiaxi-ucb** [thinkingjimmy/Learning-Prompt#64]
The 'thinkingjimmy/Learning-Prompt' repository doesn't contain the 'docs/midjourney-learning-path' path in 'main'.  
The 'thinkingjimmy/Learning-Prompt' repository doesn't contain the 'docs/chatgpt-learning-path' path in 'main'.  
希望能更新一下路径

**Comment by thinkingjimmy** [comment]
感谢提醒，已更新
