### ISSUE TITLE
一个示例错误

### ISSUE THREAD

**Issue by tailnode** [thinkingjimmy/Learning-Prompt#8]
在[场景1:问答问题](https://learningprompt.wiki/docs/tutorial-basics/%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%20&%20%E4%BD%BF%E7%94%A8%E6%8A%80%E5%B7%A7/%E5%9C%BA%E6%99%AF1%EF%BC%9A%E9%97%AE%E7%AD%94%E9%97%AE%E9%A2%98)中，我试了一下，ChatGPT能回答出今天的日期是星期几了。

**教程**
<img width="949" alt="image" src="https://user-images.githubusercontent.com/3156493/226071227-1d39f698-8986-4ba7-8edd-d3260836d50a.png">

**2023-03-18运行时的实际结果**
<img width="231" alt="image" src="https://user-images.githubusercontent.com/3156493/226071163-d2a82382-6934-4ef4-b4ab-fecdbace6c49.png">

**Comment by thinkingjimmy** [comment]
的确，之前这种星期几的问题它是可能是通过历史数据找答案，现在应该是逻辑计算了，我将其调整为「现在的美国总统是谁？」它的答案是「截至2021年9月，现任美国总统是乔·拜登（Joe Biden）。」
